export const ACTION_LOGIN = "ACTION_LOGIN";
export const ACTION_NEW_MESSAGE = "ACTION_NEW_MESSAGE";
export const ACTION_NEW_MESSAGES = "ACTION_NEW_MESSAGES";
export const ACTION_NEXT_TYPE_OF_MESSAGE = "ACTION_NEXT_TYPE_OF_MESSAGE";
